import random
import numpy as np

from typing import List, Dict, Optional



def get_create_dpo_data_prompt(prompt: str, data: List[str]) -> List[Dict]:

    prompt = f"""A language model has been given a prompt: {prompt}

The output list of it is: {data}

Your mission is to judge which data this language model generate fits the prompt most and which fits worst, and explain your judgment. 

The JSON object you output must contain the following keys:
- "reason": a string, the reason of your judgment.
- "best": a number, the index of the generated data that fits prompt the most.
- "worst": a number, the index of the generated data that fits prompt the worst.

Your output must always be a JSON object only, do not explain yourself or output anything else."""

    messages: List[Dict] = [
        {'role': 'system', 'content': 'You are a helpful assistant.'},
        {'role': 'user', 'content': prompt}
    ]
    return messages


def get_create_all_revise_data_prompt(prompt: str, data: str) -> List[Dict]:

    prompt = f"""A language model has been given a prompt: {prompt}

The output generated by the model is: {data}

Your task is to evaluate the generated output based on the following criteria:

1. Relevance: Assess whether the output directly addresses the task described in the prompt.
2. Completeness: Check if the output includes all necessary elements as specified in the prompt.
3. Accuracy: Verify if the output is factually correct and adheres to the guidelines provided in the prompt.

For each criterion, provide a brief explanation supporting your evaluation. Then, provide a revised version of the output.

Your response should be a valid JSON object containing the following keys:

- "reason": A string providing the reason for your judgment.
- "revision": A string with the revised version of the output based on your evaluation and the prompt.

Ensure your output is always a valid JSON object, formatted as a JSON string. Do not include any additional explanations or information."""

    messages: List[Dict] = [
        {'role': 'system', 'content': 'You are a helpful assistant.'},
        {'role': 'user', 'content': prompt}
    ]
    return messages